---
title: 'Changes in SEL: First Report'
author: "Klint Kanopka"
date: "May 9, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(conflicted)
library(stargazer)
source("file_paths.R")
source("read_data.R")
```

# Test 1: Smarter Balanced ELA

## Model Comparison

```{r, results='asis'}
source("test_1.R")

stargazer(model_1_t1, 
          model_2_t1, 
          model_3_t1, 
          model_4_t1, 
          #se= list(m1_t1_se,
          #         m2_t1_se,
          #         m3_t1_se,
          #         m4_t1_se),
          header=F,
          title="Smarter Balanced ELA",
          covariate.labels=c("$SEL_{GM,t-1}$",
                             "$SEL_{SA,t-1}$",
                             "$SEL_{SE,t-1}$",
                             "$SEL_{SM,t-1}$",
                             "$SEL_{GM,t-2}$", 
                             "$SEL_{SA,t-2}$",
                             "$SEL_{SE,t-2}$",
                             "$SEL_{SM,t-2}$",
                             "$TEST_{t-1}$",
                             "$TEST_{t-2}$"
                             ),
          dep.var.labels = "Scaled Test Score",
          add.lines=list(c("Individual Fixed Effects", "X", "", "", ""))
          )

```


# Test 2: Smarter Balanced Math

## Model Comparison

```{r, results='asis'}
source("test_2.R")

stargazer(model_1_t2, 
          model_2_t2, 
          model_3_t2, 
          model_4_t2, 
          #se= list(m1_t2_se,
          #         m2_t2_se,
          #         m3_t2_se,
          #         m4_t2_se),
          header=F,
          title="Smarter Balanced Math",
          covariate.labels=c("$SEL_{GM,t-1}$",
                             "$SEL_{SA,t-1}$",
                             "$SEL_{SE,t-1}$",
                             "$SEL_{SM,t-1}$",
                             "$SEL_{GM,t-2}$", 
                             "$SEL_{SA,t-2}$",
                             "$SEL_{SE,t-2}$",
                             "$SEL_{SM,t-2}$",
                             "$TEST_{t-1}$",
                             "$TEST_{t-2}$"
                             ),
          dep.var.labels = "Scaled Test Score",
          add.lines=list(c("Individual Fixed Effects", "X", "", "", ""))
          )

```